apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: esj-r4
  namespace: esj-r4
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'esj-r4-*'
      server: 'https://kubernetes.default.svc'